"""Audit subsystem (spec §5).

Coach calls `compass_audit(artifact)` whenever a worker produces a
meaningful unit of work. Compass returns a verdict and writes it to
the audit log. Audits are advisory — never blocking.

Verdicts:
  - **aligned** — silent OK to coach; logged; human not notified.
  - **confident_drift** — work clearly contradicts a >0.8 / <0.2
    statement; direct message to coach; human NOT pushed (§10.5).
  - **uncertain_drift** — work seems off but relevant statements are
    in 0.3–0.7; coach proceeds cautiously; a question is queued for
    the human (with a prediction).

Rollup safety net (§5.4): every `AUDIT_ROLLUP_INTERVAL` audits, scan
the most recent N audits for region drift. If many recent audits in
the same region drifted, queue a meta-question — the lattice may be
wrong, not the work.

**Audit reports as .md files** (Docs/kanban-specs.md §5.3): every
audit also writes a standalone markdown report to
`<compass_root>/audit_reports/<audit_id>.md`, mirrored to kDrive at
the same relative path. The .md is the human-readable surface
(opens in the Files pane, attaches to messages, browses on phone);
the jsonl drives the dashboard's audit-log filter pills + the
rollup safety net. Both written from this module so they can't
diverge.
"""

from __future__ import annotations

import asyncio
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from server.events import bus
from server.webdav import webdav

from server.compass import config, llm, prompts, store
from server.compass.paths import compass_paths, ensure_compass_scaffold, remote_path
from server.compass.store import (
    AuditRecord,
    LatticeState,
    Question,
)

logger = logging.getLogger("harness.compass.audit")
if not logger.handlers:
    h = logging.StreamHandler(sys.stdout)
    h.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s | %(message)s"))
    logger.addHandler(h)
    logger.setLevel(logging.INFO)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


VALID_VERDICTS = ("aligned", "confident_drift", "uncertain_drift")


# Map verdict tokens to a human-readable display label. Used in the
# .md report header so a non-LLM reader skimming the report knows
# right away whether action is needed.
_VERDICT_LABELS: dict[str, str] = {
    "aligned": "Aligned (no action)",
    "confident_drift": "Confident drift (Coach action needed)",
    "uncertain_drift": "Uncertain drift (queued question for human)",
}


def _format_audit_report(
    *, record: AuditRecord, state: LatticeState
) -> str:
    """Compose the markdown body for a single audit's report file.

    Lattice statements referenced in `contradicting_ids` are inlined
    verbatim (id, weight, text) so the report stands on its own — even
    if a statement later gets archived or reformulated, the report
    still tells the reader what was being contradicted at the time.
    Statements that no longer exist on the lattice are still listed
    by id with a `(no longer in lattice)` note; better than dropping
    them silently.
    """
    by_id = {s.id: s for s in state.statements}
    lines: list[str] = [
        f"# Audit {record.id}",
        "",
        f"- **Verdict:** {_VERDICT_LABELS.get(record.verdict, record.verdict)}",
        f"- **When:** {record.ts}",
    ]
    if record.question_id:
        lines.append(f"- **Question queued:** {record.question_id}")
    lines.append("")

    # Artifact body — surfaced verbatim so the human can read the work
    # the audit was about. Wrapped in a fenced block to keep markdown
    # rendering predictable when the artifact contains its own headings.
    if record.artifact:
        lines.append("## Artifact")
        lines.append("")
        lines.append("```")
        lines.append(record.artifact.rstrip())
        lines.append("```")
        lines.append("")

    summary = (record.summary or "").strip()
    if summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    msg = (record.message_to_coach or "").strip()
    if msg:
        lines.append("## Message to Coach")
        lines.append("")
        lines.append(msg)
        lines.append("")

    lines.append("## Contradicting lattice statements")
    lines.append("")
    if record.contradicting_ids:
        for sid in record.contradicting_ids:
            stmt = by_id.get(sid)
            if stmt is None:
                lines.append(f"- **{sid}** _(no longer in lattice)_")
                continue
            weight = getattr(stmt, "weight", None)
            weight_part = f" (weight {weight:.2f})" if weight is not None else ""
            text = (getattr(stmt, "text", "") or "").strip()
            lines.append(f"- **{sid}**{weight_part}: {text}")
    else:
        lines.append("_(none)_")
    lines.append("")
    lines.append("---")
    lines.append(
        "_Generated by the Compass audit-watcher. The structured "
        "record lives in `audits.jsonl`; this file is the human-"
        "readable mirror._"
    )
    return "\n".join(lines) + "\n"


def _atomic_write_text(target: Path, content: str) -> None:
    """Atomic write via tempfile + os.replace. Mirrors the helper in
    server/tasks.py so a partial Compass write doesn't leave a
    truncated report behind."""
    import os as _os
    import tempfile as _tempfile
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = _tempfile.mkstemp(
        prefix=target.name + ".", suffix=".tmp", dir=str(target.parent)
    )
    try:
        with _os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        _os.replace(tmp_path, target)
    except Exception:
        try:
            _os.unlink(tmp_path)
        except OSError:
            pass
        raise


async def write_audit_report_md(
    project_id: str, record: AuditRecord, state: LatticeState
) -> tuple[str, str] | None:
    """Persist the markdown report alongside the jsonl entry. Returns
    `(local_relative, remote_path)` on success, or None on failure.

    Local-write failures are logged and swallowed — a report write
    issue must not block the audit's structured persistence (the
    jsonl is the source of truth; the .md is a derived view). kDrive
    mirror is fire-and-forget.
    """
    try:
        ensure_compass_scaffold(project_id)
        cp = compass_paths(project_id)
        cp.audit_reports_dir.mkdir(parents=True, exist_ok=True)
        target = cp.audit_report_for(record.id)
        body = _format_audit_report(record=record, state=state)
        _atomic_write_text(target, body)
    except Exception:
        logger.exception("compass.audit: write_audit_report_md failed")
        return None

    # Relative path stored on tasks.compass_audit_report_path. Format
    # `projects/<id>/working/compass/audit_reports/<audit_id>.md` —
    # the data-harness-path link mechanism's expected shape.
    local_rel = (
        f"projects/{project_id}/working/compass/audit_reports/{record.id}.md"
    )
    remote_rel = remote_path(project_id, "audit_reports", f"{record.id}.md")

    if webdav.enabled:
        # Fire-and-forget; failure is logged inside webdav.write_text.
        try:
            asyncio.create_task(webdav.write_text(remote_rel, body))
        except Exception:
            logger.exception(
                "compass.audit: kDrive mirror task creation failed"
            )

    return local_rel, remote_rel


async def audit_work(project_id: str, artifact: str) -> dict[str, Any]:
    """Audit a work artifact against the lattice. Persists to
    audits.jsonl and (for uncertain_drift) queues a question.

    Returns a dict in the shape of `compass_audit`'s MCP contract.
    Raises only on configuration errors; LLM/parse failures degrade
    to an `aligned` verdict with a diagnostic in `summary`.
    """
    # Use load_with_meta so the audit prompt is anchored on the
    # project's identity (not the harness's). Without this, audit
    # output would happily reason about agent slot names and other
    # harness chatter as if they were project-domain content.
    state = await store.load_with_meta(project_id)
    artifact = (artifact or "").strip()
    if not artifact:
        return _empty_audit_response("empty artifact")

    try:
        res = await llm.call(
            prompts.AUDIT_SYSTEM,
            prompts.audit_user(state, artifact),
            max_tokens=config.LLM_MAX_TOKENS_AUDIT,
            project_id=project_id,
            label="compass:audit",
        )
        parsed = llm.parse_json_safe(res.text) or {}
    except Exception:
        logger.exception("compass.audit: LLM call failed")
        return _empty_audit_response("audit LLM call failed; defaulting to aligned")

    verdict = str(parsed.get("verdict") or "aligned").strip()
    if verdict not in VALID_VERDICTS:
        verdict = "aligned"
    summary = str(parsed.get("summary") or "").strip()
    contradicting = _sanitize_str_list(parsed.get("contradicting_ids"))
    message_to_coach = str(parsed.get("message_to_coach") or "").strip()

    audit_id = store.next_audit_id()
    question_id: str | None = None

    if verdict == "uncertain_drift":
        q_for = parsed.get("question_for_human")
        if isinstance(q_for, dict):
            qtext = str(q_for.get("q") or "").strip()
            qpred = str(q_for.get("prediction") or "").strip()
            qtargets = _sanitize_str_list(q_for.get("targets"))
            if qtext and qpred:
                question_id = await _queue_question_from_audit(
                    project_id=project_id,
                    state=state,
                    qtext=qtext,
                    qprediction=qpred,
                    qtargets=qtargets,
                    audit_id=audit_id,
                    audit_summary=summary,
                )

    record = AuditRecord(
        id=audit_id,
        ts=_now_iso(),
        artifact=artifact,
        verdict=verdict,
        summary=summary,
        contradicting_ids=contradicting,
        message_to_coach=message_to_coach,
        question_id=question_id,
    )
    await store.append_audit(project_id, record)

    # Write the human-readable .md report alongside the jsonl. Failure
    # here is logged + swallowed; jsonl is the source of truth.
    md_paths = await write_audit_report_md(project_id, record, state)
    report_path_local = md_paths[0] if md_paths else None

    # Bus event so the dashboard updates the audit log live + the
    # kanban subscriber sees the verdict and (informationally)
    # mirrors compass_audit_report_path / compass_audit_verdict onto
    # the relevant task row.
    try:
        await bus.publish({
            "ts": record.ts,
            "agent_id": "compass",
            "project_id": project_id,
            "type": "compass_audit_logged",
            "audit_id": record.id,
            "verdict": record.verdict,
            "contradicting_ids": record.contradicting_ids,
            "question_id": record.question_id,
            # report_path enables single-click open in the Files pane;
            # the kanban card's "compass: aligned/drift" pip links here.
            "report_path": report_path_local,
        })
    except Exception:
        logger.exception("compass.audit: bus publish failed")

    # Rollup check — only on confident/uncertain drift; aligned audits
    # don't motivate a meta-review.
    if verdict in ("confident_drift", "uncertain_drift"):
        try:
            await _maybe_rollup_meta_question(project_id)
        except Exception:
            logger.exception("compass.audit: rollup check failed")

    return {
        "verdict": record.verdict,
        "summary": record.summary,
        "contradicting_ids": record.contradicting_ids,
        "message_to_coach": record.message_to_coach,
        "question_id": record.question_id,
    }


async def _queue_question_from_audit(
    *,
    project_id: str,
    state: LatticeState,
    qtext: str,
    qprediction: str,
    qtargets: list[str],
    audit_id: str,
    audit_summary: str,
) -> str:
    """Append an audit-driven question to questions.json. Returns id."""
    qid = store.next_question_id(state)
    q = Question(
        id=qid,
        q=qtext,
        prediction=qprediction,
        targets=qtargets,
        rationale=f"Generated from audit drift: {audit_summary}"[:500],
        asked_at=_now_iso(),
        asked_in_run="audit",
        from_audit=audit_id,
    )
    state.questions.append(q)
    await store.save_questions(project_id, state.questions)
    try:
        await bus.publish({
            "ts": _now_iso(),
            "agent_id": "compass",
            "project_id": project_id,
            "type": "compass_question_queued",
            "question_id": qid,
            "from_audit": audit_id,
        })
    except Exception:
        logger.exception("compass.audit: question_queued publish failed")
    return qid


async def _maybe_rollup_meta_question(project_id: str) -> None:
    """Spec §5.4 safety net: every Nth audit, scan recent drifts. If
    a single region accumulates ≥ 3 drift verdicts in the last
    `AUDIT_ROLLUP_INTERVAL` audits, queue a meta-question about
    that region. Heuristic — the spec leaves the threshold loose;
    we pick conservative values.
    """
    interval = config.AUDIT_ROLLUP_INTERVAL
    if interval <= 0:
        return
    audits = store.read_audits(project_id)
    if len(audits) < interval or len(audits) % interval != 0:
        return

    recent = audits[-interval:]
    drifts = [a for a in recent if a.verdict in ("confident_drift", "uncertain_drift")]
    if len(drifts) < 3:
        return

    # Map contradicting statement ids to regions to find concentration.
    state = store.load_state(project_id)
    by_id = {s.id: s for s in state.statements}
    region_counts: dict[str, int] = {}
    for a in drifts:
        for sid in a.contradicting_ids:
            stmt = by_id.get(sid)
            if not stmt:
                continue
            region_counts[stmt.region] = region_counts.get(stmt.region, 0) + 1
    if not region_counts:
        return
    top_region, top_count = max(region_counts.items(), key=lambda kv: kv[1])
    if top_count < 3:
        return

    # Don't double-queue: skip if a meta-question for this region is
    # already pending.
    pending_q = [
        q for q in state.questions
        if not q.digested and not q.contradicted
        and q.from_audit is None
        and "lattice may be wrong" in q.q.lower()
        and top_region in q.q.lower()
    ]
    if pending_q:
        return

    qid = store.next_question_id(state)
    meta_q = Question(
        id=qid,
        q=(
            f"Most recent worker outputs in the '{top_region}' region have drifted "
            "from the lattice. Is the lattice may be wrong about {region}? "
            "(Yes = the lattice needs revision; No = workers need redirection.)"
            .replace("{region}", top_region)
        ),
        prediction="The lattice probably needs revision in this region.",
        targets=[],
        rationale=(
            f"Audit rollup: {top_count} of the last {interval} audits drifted "
            f"in '{top_region}'."
        ),
        asked_at=_now_iso(),
        asked_in_run="audit-rollup",
        from_audit=None,
    )
    state.questions.append(meta_q)
    await store.save_questions(project_id, state.questions)
    try:
        await bus.publish({
            "ts": _now_iso(),
            "agent_id": "compass",
            "project_id": project_id,
            "type": "compass_question_queued",
            "question_id": qid,
            "rollup_region": top_region,
            "rollup_count": top_count,
        })
    except Exception:
        logger.exception("compass.audit: rollup publish failed")


def _empty_audit_response(reason: str) -> dict[str, Any]:
    return {
        "verdict": "aligned",
        "summary": reason,
        "contradicting_ids": [],
        "message_to_coach": "OK · aligned with lattice (degraded)",
        "question_id": None,
    }


def _sanitize_str_list(raw: Any) -> list[str]:
    if not isinstance(raw, list):
        return []
    return [str(x).strip() for x in raw if isinstance(x, (str, int, float)) and str(x).strip()]


__all__ = ["audit_work", "VALID_VERDICTS"]
