#!/usr/bin/env bash
# Make pytest runnable from the current git worktree.
#
# `.venv` is gitignored and not copied by `git worktree add`, so a
# fresh worktree (e.g. an Agent({isolation: "worktree"}) checkout) has
# no Python deps. Run this script from the worktree root.
#
# Behaviour:
#   1. If THIS worktree's `.venv` already has pytest → no-op.
#   2. Else if we're in the main worktree → `uv sync --extra dev`
#      (or pip fallback). This builds binary deps from source, so on
#      win32-ARM64 (no prebuilt cryptography / httptools wheels) it
#      will fail without MSVC + Rust. That's a one-time host-setup
#      problem, not a script bug.
#   3. Else (sub-worktree) → REUSE the main worktree's existing
#      `.venv` via a `./pytest` shim that exports PYTHONPATH=<this
#      worktree>. No per-worktree binary build, no broken sub-trees.
set -euo pipefail

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not inside a git worktree." >&2
  exit 1
fi

CURRENT="$(git rev-parse --show-toplevel)"
# `git worktree list --porcelain` first line is `worktree <path>`. Use
# sed (not `awk '{print $2}'`) so paths containing spaces survive.
MAIN="$(git worktree list --porcelain | sed -n '1s/^worktree //p')"
cd "$CURRENT"

# Pick the python inside a venv path (Windows = Scripts, POSIX = bin).
venv_python() {
  local venv="$1"
  if [ -x "$venv/Scripts/python.exe" ]; then echo "$venv/Scripts/python.exe"
  elif [ -x "$venv/Scripts/python" ];  then echo "$venv/Scripts/python"
  elif [ -x "$venv/bin/python" ];      then echo "$venv/bin/python"
  fi
}

# Step 1 — fast path: this worktree already has a usable .venv.
LOCAL_PY=$(venv_python "$CURRENT/.venv")
if [ -n "$LOCAL_PY" ] && "$LOCAL_PY" -c 'import pytest' >/dev/null 2>&1; then
  echo "Already bootstrapped. Run tests with:"
  echo "  $LOCAL_PY -m pytest"
  exit 0
fi

# Step 2 — main worktree, needs an install.
if [ "$CURRENT" = "$MAIN" ]; then
  if command -v uv >/dev/null 2>&1; then
    uv sync --extra dev
    echo
    echo "Main worktree bootstrapped. Run tests with:"
    echo "  uv run pytest"
  else
    PY=$(command -v python || command -v python3 || true)
    [ -n "$PY" ] || { echo "No python on PATH." >&2; exit 1; }
    "$PY" -m venv .venv
    VENV_PY=$(venv_python ".venv")
    "$VENV_PY" -m pip install --upgrade pip
    "$VENV_PY" -m pip install -e ".[dev]"
    echo
    echo "Main worktree bootstrapped. Run tests with:"
    echo "  $VENV_PY -m pytest"
  fi
  exit 0
fi

# Step 3 — sub-worktree: reuse main's .venv.
MAIN_PY=$(venv_python "$MAIN/.venv")
if [ -z "$MAIN_PY" ] || ! "$MAIN_PY" -c 'import pytest' >/dev/null 2>&1; then
  echo "Main worktree at '$MAIN' has no usable .venv with pytest."
  echo "Bootstrap the main worktree first:"
  echo "  bash '$MAIN/scripts/bootstrap_worktree.sh'"
  exit 1
fi

# Drop a thin shim so agents can just `./pytest` (or `bash pytest`)
# without typing the env-var dance every time. PYTHONPATH=$CURRENT puts
# THIS worktree's source ahead of the main's editable .pth entry.
cat > "./pytest" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/bootstrap_worktree.sh — runs pytest against
# THIS worktree's source using the main worktree's .venv.
exec env PYTHONPATH="$CURRENT" "$MAIN_PY" -m pytest "\$@"
EOF
chmod +x "./pytest"

echo
echo "Sub-worktree wired to main .venv at:"
echo "  $MAIN_PY"
echo
echo "Run tests with:"
echo "  ./pytest                 # or any pytest args, e.g. ./pytest server/tests/test_db.py"
